// Known gaming franchises and series for title matching.
// Ordered by priority — longer/more specific names come first.
// Extraction strategies:
//   1. Direct prefix match: "Star Wars: Jedi Survivor" → "Star Wars"
//   2. Known suffix: "LEGO Star Wars: The Skywalker Saga" → "LEGO Star Wars"
//   3. Roman numeral / sequel marker: "Witcher 3: Wild Hunt" → "Witcher"

const FRANCHISES = [
  // ── Major ──────────────────────────────────────────
  { names: ['Star Wars'], patterns: [/^star wars/i] },
  { names: ['LEGO Star Wars'], patterns: [/^lego star wars/i] },
  { names: ['LEGO Harry Potter'], patterns: [/^lego harr?y potter/i] },
  { names: ['LEGO Batman'], patterns: [/^lego batman/i] },
  { names: ['LEGO Marvel'], patterns: [/^lego marvel/i] },
  { names: ['LEGO DC'], patterns: [/^lego dc/i] },
  { names: ['LEGO The Lord of the Rings'], patterns: [/^lego (?:the )?lord of the rings/i] },
  { names: ['LEGO', 'LEGO Games'], patterns: [/^lego\b/i] },
  { names: ['Harry Potter'], patterns: [/^harr?y potter/i] },
  { names: ['The Lord of the Rings'], patterns: [/^(?:the )?lord of the rings/i] },
  { names: ['Middle-earth'], patterns: [/^middle.earth/i] },
  { names: ['Assassin\'s Creed'], patterns: [/^assassins?['’]?\s*creed/i] },
  { names: ['Call of Duty'], patterns: [/^call of duty/i] },
  { names: ['Battlefield'], patterns: [/^battlefield\b/i] },
  { names: ['Far Cry'], patterns: [/^far cry\b/i] },
  { names: ['Grand Theft Auto', 'GTA'], patterns: [/^grand theft auto/i] },
  { names: ['Red Dead Redemption', 'Red Dead'], patterns: [/^red dead redemption/i] },
  { names: ['The Witcher', 'Witcher'], patterns: [/^(?:the )?witcher\b/i] },
  { names: ['Cyberpunk 2077'], patterns: [/^cyberpunk 2077/i] },
  { names: ['Mortal Kombat'], patterns: [/^mortal kombat/i] },
  { names: ['Injustice'], patterns: [/^injustice\b/i] },
  { names: ['Batman: Arkham', 'Arkham'], patterns: [/^batman/i] },
  { names: ['Spider-Man'], patterns: [/^spider.man/i] },
  { names: ['Marvel'], patterns: [/^marvel\b/i] },
  { names: ['DC Universe', 'DC'], patterns: [/^dc\b/i] },
  { names: ['Final Fantasy'], patterns: [/^final fantasy/i] },
  { names: ['Kingdom Hearts'], patterns: [/^kingdom hearts/i] },
  { names: ['Dragon Quest'], patterns: [/^dragon quest/i] },
  { names: ['Persona'], patterns: [/^persona\b/i] },
  { names: ['Shin Megami Tensei', 'SMT'], patterns: [/^shin megami tensei/i] },
  { names: ['Metal Gear Solid', 'Metal Gear'], patterns: [/^metal gear solid/i] },
  { names: ['Resident Evil'], patterns: [/^resident evil/i] },
  { names: ['Silent Hill'], patterns: [/^silent hill/i] },
  { names: ['Dead Space'], patterns: [/^dead space/i] },
  { names: ['Elden Ring'], patterns: [/^elden ring/i] },
  { names: ['Dark Souls'], patterns: [/^dark souls/i] },
  { names: ['Bloodborne'], patterns: [/^bloodborne/i] },
  { names: ['Sekiro'], patterns: [/^sekiro/i] },
  { names: ['The Elder Scrolls'], patterns: [/^(?:the )?elder scrolls/i] },
  { names: ['Fallout'], patterns: [/^fallout\b/i] },
  { names: ['Doom'], patterns: [/^doom\b/i] },
  { names: ['Wolfenstein'], patterns: [/^wolfenstein/i] },
  { names: ['Half-Life'], patterns: [/^half.life/i] },
  { names: ['Portal'], patterns: [/^portal\b/i] },
  { names: ['Left 4 Dead'], patterns: [/^left 4 dead/i] },
  { names: ['Team Fortress'], patterns: [/^team fortress/i] },
  { names: ['Counter-Strike'], patterns: [/^counter.strike/i] },
  { names: ['Dota', 'Dota 2'], patterns: [/^dota\b/i] },
  { names: ['Overwatch'], patterns: [/^overwatch/i] },
  { names: ['Diablo'], patterns: [/^diablo/i] },
  { names: ['Warcraft'], patterns: [/^warcraft/i] },
  { names: ['Starcraft'], patterns: [/^starcraft/i] },
  { names: ['World of Warcraft', 'WoW'], patterns: [/^world of warcraft/i] },
  { names: ['Hearthstone'], patterns: [/^hearthstone/i] },
  { names: ['Overcooked'], patterns: [/^overcooked/i] },
  { names: ['Borderlands'], patterns: [/^borderlands/i] },
  { names: ['BioShock'], patterns: [/^bioshock/i] },
  { names: ['Dishonored'], patterns: [/^dishonored/i] },
  { names: ['Prey'], patterns: [/^prey\b/i] },
  { names: ['Deus Ex'], patterns: [/^deus ex/i] },
  { names: ['System Shock'], patterns: [/^system shock/i] },
  { names: ['Thief'], patterns: [/^thief\b/i] },
  { names: ['Tomb Raider'], patterns: [/^tomb raider/i] },
  { names: ['Uncharted'], patterns: [/^uncharted/i] },
  { names: ['The Last of Us'], patterns: [/^(?:the )?last of us/i] },
  { names: ['God of War'], patterns: [/^god of war/i] },
  { names: ['Horizon'], patterns: [/^horizon\b/i] },
  { names: ['Days Gone'], patterns: [/^days gone/i] },
  { names: ['Ghost of Tsushima'], patterns: [/^ghost of tsushima/i] },
  { names: ['Ratchet & Clank'], patterns: [/^ratchet & clank/i] },
  { names: ['Jak and Daxter'], patterns: [/^jak (?:and|&) daxter/i] },
  { names: ['Sly Cooper'], patterns: [/^sly cooper/i] },
  { names: ['Crash Bandicoot'], patterns: [/^crash bandicoot/i] },
  { names: ['Spyro'], patterns: [/^spyro\b/i] },
  { names: ['Sonic the Hedgehog', 'Sonic'], patterns: [/^sonic\b/i] },
  { names: ['Super Mario', 'Mario'], patterns: [/^super mario|^mario\b/i] },
  { names: ['The Legend of Zelda', 'Zelda'], patterns: [/^(?:the )?legend of zelda|^zelda\b/i] },
  { names: ['Metroid'], patterns: [/^metroid/i] },
  { names: ['Pokémon', 'Pokemon'], patterns: [/^pok[eé]mon/i] },
  { names: ['Kirby'], patterns: [/^kirby\b/i] },
  { names: ['Donkey Kong'], patterns: [/^donkey kong/i] },
  { names: ['Fire Emblem'], patterns: [/^fire emblem/i] },
  { names: ['Xenoblade'], patterns: [/^xenoblade/i] },
  { names: ['Bayonetta'], patterns: [/^bayonetta/i] },
  { names: ['Devil May Cry'], patterns: [/^devil may cry/i] },
  { names: ['Street Fighter'], patterns: [/^street fighter/i] },
  { names: ['Tekken'], patterns: [/^tekken\b/i] },
  { names: ['Mortal Kombat'], patterns: [/^mortal kombat/i] },
  { names: ['Guilty Gear'], patterns: [/^guilty gear/i] },
  { names: ['Dragon Ball', 'Dragon Ball Z'], patterns: [/^dragon ball/i] },
  { names: ['Naruto'], patterns: [/^naruto\b/i] },
  { names: ['One Piece'], patterns: [/^one piece/i] },
  { names: ['Attack on Titan'], patterns: [/^attack on titan/i] },
  { names: ['My Hero Academia', 'MHA'], patterns: [/^my hero academia/i] },
  { names: ['Demon Slayer'], patterns: [/^demon slayer/i] },
  { names: ['Ju-Jutsu Kaisen'], patterns: [/^jujutsu kaisen|jujitsu kaisen/i] },
  { names: ['FIFA'], patterns: [/^fifa/i] },
  { names: ['Madden NFL'], patterns: [/^madden/i] },
  { names: ['NBA 2K'], patterns: [/^nba 2k/i] },
  { names: ['NBA'], patterns: [/^nba\b/i] },
  { names: ['PES', 'eFootball'], patterns: [/^pes\b|^efootball/i] },
  { names: ['Pro Evolution Soccer'], patterns: [/^pro evolution soccer/i] },
  { names: ['Football Manager'], patterns: [/^football manager/i] },
  { names: ['Forza'], patterns: [/^forza\b/i] },
  { names: ['Gran Turismo'], patterns: [/^gran turismo/i] },
  { names: ['Need for Speed'], patterns: [/^need for speed/i] },
  { names: ['Burnout'], patterns: [/^burnout\b/i] },
  { names: ['The Sims'], patterns: [/^(?:the )?sims\b/i] },
  { names: ['SimCity'], patterns: [/^simcity/i] },
  { names: ['Cities: Skylines'], patterns: [/^cities: skylines/i] },
  { names: ['Planet Coaster'], patterns: [/^planet coaster/i] },
  { names: ['Planet Zoo'], patterns: [/^planet zoo/i] },
  { names: ['RollerCoaster Tycoon'], patterns: [/^rollercoaster tycoon|roller coaster tycoon/i] },
  { names: ['Age of Empires'], patterns: [/^age of empires/i] },
  { names: ['Age of Mythology'], patterns: [/^age of mythology/i] },
  { names: ['Civilization', 'Sid Meier\'s Civilization'], patterns: [/^civilization|^sid meiers? civilization/i] },
  { names: ['Sid Meier\'s'], patterns: [/^sid meiers?/i] },
  { names: ['Total War'], patterns: [/^total war/i] },
  { names: ['Company of Heroes'], patterns: [/^company of heroes/i] },
  { names: ['Warhammer', 'Warhammer 40k'], patterns: [/^warhammer/i] },
  { names: ['XCOM'], patterns: [/^xcom\b/i] },
  { names: ['Halo'], patterns: [/^halo\b/i] },
  { names: ['Gears of War'], patterns: [/^gears of war/i] },
  { names: ['Mass Effect'], patterns: [/^mass effect/i] },
  { names: ['Dragon Age'], patterns: [/^dragon age/i] },
  { names: ['Starfield'], patterns: [/^starfield/i] },
  { names: ['Skyrim'], patterns: [/^skyrim/i] },
  { names: ['Oblivion'], patterns: [/^oblivion/i] },
  { names: ['Morrowind'], patterns: [/^morrowind/i] },
  { names: ['Baldur\'s Gate'], patterns: [/^baldurs?['’]?\s*gate/i] },
  { names: ['Neverwinter Nights'], patterns: [/^neverwinter nights/i] },
  { names: ['Planescape'], patterns: [/^planescape/i] },
  { names: ['Icewind Dale'], patterns: [/^icewind dale/i] },
  { names: ['Divinity: Original Sin', 'Divinity'], patterns: [/^divinity/i] },
  { names: ['Pathfinder'], patterns: [/^pathfinder/i] },
  { names: ['Pillars of Eternity'], patterns: [/^pillars of eternity/i] },
  { names: ['Tyranny'], patterns: [/^tyranny\b/i] },
  { names: ['Wasteland'], patterns: [/^wasteland/i] },
  { names: ['Shadowrun'], patterns: [/^shadowrun/i] },
  { names: ['Deus Ex'], patterns: [/^deus ex/i] },
  { names: ['Thief'], patterns: [/^thief\b/i] },
  { names: ['Tomb Raider'], patterns: [/^tomb raider/i] },
  { names: ['Hitman'], patterns: [/^hitman\b/i] },
  { names: ['Just Cause'], patterns: [/^just cause/i] },
  { names: ['Sleeping Dogs'], patterns: [/^sleeping dogs/i] },
  { names: ['Mad Max'], patterns: [/^mad max/i] },
  { names: ['Dying Light'], patterns: [/^dying light/i] },
  { names: ['Dead Island'], patterns: [/^dead island/i] },
  { names: ['Metro'], patterns: [/^metro\b/i] },
  { names: ['S.T.A.L.K.E.R.'], patterns: [/^stalker/i] },
  { names: ['Crysis'], patterns: [/^crysis/i] },
  { names: ['Prince of Persia'], patterns: [/^prince of persia/i] },
  { names: ['Rayman'], patterns: [/^rayman\b/i] },
  { names: ['Assassin\'s Creed'], patterns: [/^assassins? creed/i] },
  { names: ['Far Cry'], patterns: [/^far cry\b/i] },
  { names: ['Watch Dogs'], patterns: [/^watch dogs/i] },
  { names: ['The Division'], patterns: [/^(?:the )?division/i] },
  { names: ['Ghost Recon'], patterns: [/^ghost recon/i] },
  { names: ['Rainbow Six'], patterns: [/^rainbow six/i] },
  { names: ['Splinter Cell'], patterns: [/^splinter cell/i] },
  { names: ['Might & Magic', 'Heroes of Might & Magic'], patterns: [/^might & magic|^heroes of might|^mights? & magic/i] },
  { names: ['Heroes of Might & Magic'], patterns: [/^heroes of might/i] },
  { names: ['King\'s Bounty'], patterns: [/^kings? bounty/i] },
  { names: ['Disciples'], patterns: [/^disciples\b/i] },
  { names: ['Sacred'], patterns: [/^sacred\b/i] },
  { names: ['Gothic'], patterns: [/^gothic\b/i] },
  { names: ['Risen'], patterns: [/^risen\b/i] },
  { names: ['Elex'], patterns: [/^elex\b/i] },
  { names: ['Two Worlds'], patterns: [/^two worlds/i] },
  { names: ['Fable'], patterns: [/^fable\b/i] },
  { names: ['The Legend of Zelda', 'Zelda'], patterns: [/^zelda/i] },
  { names: ['Hollow Knight'], patterns: [/^hollow knight/i] },
  { names: ['Dead Cells'], patterns: [/^dead cells/i] },
  { names: ['Hades'], patterns: [/^hades\b/i] },
  { names: ['Bastion'], patterns: [/^bastion\b/i] },
  { names: ['Transistor'], patterns: [/^transistor/i] },
  { names: ['Pyre'], patterns: [/^pyre\b/i] },
  { names: ['Celeste'], patterns: [/^celeste\b/i] },
  { names: ['Stardew Valley'], patterns: [/^stardew valley/i] },
  { names: ['Terraria'], patterns: [/^terraria/i] },
  { names: ['Minecraft'], patterns: [/^minecraft/i] },
  { names: ['RimWorld'], patterns: [/^rimworld/i] },
  { names: ['Factorio'], patterns: [/^factorio/i] },
  { names: ['Satisfactory'], patterns: [/^satisfactory/i] },
  { names: ['Subnautica'], patterns: [/^subnautica/i] },
  { names: ['The Forest'], patterns: [/^(?:the )?forest\b/i] },
  { names: ['Sons of the Forest'], patterns: [/^sons of the forest/i] },
  { names: ['Grounded'], patterns: [/^grounded/i] },
  { names: ['Valheim'], patterns: [/^valheim/i] },
  { names: ['No Man\'s Sky'], patterns: [/^no mans? sky/i] },
  { names: ['Elite Dangerous'], patterns: [/^elite dangerous/i] },
  { names: ['Kerbal Space Program', 'KSP'], patterns: [/^kerbal space/i] },
  { names: ['Space Engineers'], patterns: [/^space engineers/i] },
  { names: ['Euro Truck Simulator', 'American Truck Simulator', 'Truck Sim'], patterns: [/^euro truck|^american truck|truck simulator/i] },
  { names: ['Farming Simulator'], patterns: [/^farming simulator/i] },
  { names: ['Cities: Skylines'], patterns: [/^cities skylines/i] },
  { names: ['Prison Architect'], patterns: [/^prison architect/i] },
  { names: ['Tropico'], patterns: [/^tropico\b/i] },
  { names: ['Surviving Mars'], patterns: [/^surviving mars/i] },
  { names: ['Anno'], patterns: [/^anno\b/i] },
  { names: ['Settlers'], patterns: [/^settlers?\b/i] },
  { names: ['Port Royale'], patterns: [/^port royale/i] },
  { names: ['Patrician'], patterns: [/^patrician/i] },
  { names: ['Railway Empire'], patterns: [/^railway empire/i] },
  { names: ['Transport Fever'], patterns: [/^transport fever/i] },
  { names: ['OpenTTD'], patterns: [/^openttd/i] },
  { names: ['Stellaris'], patterns: [/^stellaris/i] },
  { names: ['Crusader Kings'], patterns: [/^crusader kings/i] },
  { names: ['Europa Universalis'], patterns: [/^europa universalis/i] },
  { names: ['Victoria'], patterns: [/^victoria\b/i] },
  { names: ['Hearts of Iron'], patterns: [/^hearts of iron/i] },
  { names: ['Imperator: Rome'], patterns: [/^imperator/i] },
  { names: ['Cities in Motion'], patterns: [/^cities in motion/i] },
  { names: ['Surviving the Aftermath'], patterns: [/^surviving the aftermath/i] },
  { names: ['Endzone'], patterns: [/^endzone\b/i] },
  { names: ['Banished'], patterns: [/^banished/i] },
  { names: ['Frostpunk'], patterns: [/^frostpunk/i] },
  { names: ['This War of Mine'], patterns: [/^this war of mine/i] },
  { names: ['Papers, Please'], patterns: [/^papers please/i] },
  { names: ['Return of the Obra Dinn'], patterns: [/^obra dinn/i] },
  { names: ['Disco Elysium'], patterns: [/^disco elysium/i] },
  { names: ['Undertale'], patterns: [/^undertale/i] },
  { names: ['Deltarune'], patterns: [/^deltarune/i] },
  { names: ['Cuphead'], patterns: [/^cuphead/i] },
  { names: ['Shovel Knight'], patterns: [/^shovel knight/i] },
  { names: ['Hotline Miami'], patterns: [/^hotline miami/i] },
  { names: ['Katana Zero'], patterns: [/^katana zero/i] },
  { names: ['Hyper Light Drifter'], patterns: [/^hyper light drifter/i] },
  { names: ['Risk of Rain'], patterns: [/^risk of rain/i] },
  { names: ['Slay the Spire'], patterns: [/^slay the spire/i] },
  { names: ['Monster Train'], patterns: [/^monster train/i] },
  { names: ['Griftlands'], patterns: [/^griftlands/i] },
  { names: ['Into the Breach'], patterns: [/^into the breach/i] },
  { names: ['FTL'], patterns: [/^ftl\b/i] },
  { names: ['Darkest Dungeon'], patterns: [/^darkest dungeon/i] },
  { names: ['Battle Brothers'], patterns: [/^battle brothers/i] },
  { names: ['XCOM'], patterns: [/^xcom\b/i] },
  { names: ['Phoenix Point'], patterns: [/^phoenix point/i] },
  { names: ['Mutant Year Zero'], patterns: [/^mutant year zero/i] },
  { names: ['The Banner Saga'], patterns: [/^banner saga/i] },
  { names: ['Shadow Tactics'], patterns: [/^shadow tactics/i] },
  { names: ['Desperados'], patterns: [/^desperados/i] },
  { names: ['Commandos'], patterns: [/^commandos\b/i] },
  { names: ['Syberia'], patterns: [/^syberia\b/i] },
  { names: ['The Walking Dead'], patterns: [/^walking dead/i] },
  { names: ['The Wolf Among Us'], patterns: [/^wolf among us/i] },
  { names: ['Batman: The Telltale Series', 'Telltale'], patterns: [/^batman: (?:the )?telltale|^the wolf among us|^tales from the borderlands|^game of thrones: (?:a )?telltale/i] },
  { names: ['Life is Strange'], patterns: [/^life is strange/i] },
  { names: ['Beyond: Two Souls'], patterns: [/^beyond two souls/i] },
  { names: ['Heavy Rain'], patterns: [/^heavy rain/i] },
  { names: ['Detroit: Become Human'], patterns: [/^detroit: become human/i] },
  { names: ['Until Dawn'], patterns: [/^until dawn/i] },
  { names: ['The Quarry'], patterns: [/^the quarry/i] },
  { names: ['Dark Pictures', 'The Dark Pictures Anthology'], patterns: [/^dark pictures/i] },
  { names: ['Little Nightmares'], patterns: [/^little nightmares/i] },
  { names: ['Inside'], patterns: [/^inside\b/i] },
  { names: ['Limbo'], patterns: [/^limbo\b/i] },
  { names: ['Braid'], patterns: [/^braid\b/i] },
  { names: ['Fez'], patterns: [/^fez\b/i] },
  { names: ['Super Meat Boy'], patterns: [/^super meat boy/i] },
  { names: ['The Binding of Isaac'], patterns: [/^(?:the )?binding of isaac/i] },
  { names: ['Enter the Gungeon'], patterns: [/^enter the gungeon/i] },
  { names: ['Nuclear Throne'], patterns: [/^nuclear throne/i] },
  { names: ['Vampire Survivors'], patterns: [/^vampire survivors/i] },
  { names: ['Brotato'], patterns: [/^brotato/i] },
  { names: ['20 Minutes Till Dawn'], patterns: [/^20 minutes till dawn/i] },
  { names: ['Boneraiser Minions'], patterns: [/^boneraiser/i] },
  { names: ['Soulstone Survivors'], patterns: [/^soulstone survivors/i] },
  { names: ['Spelunky'], patterns: [/^spelunky/i] },
  { names: ['Rogue Legacy'], patterns: [/^rogue legacy/i] },
  { names: ['Prison Architect'], patterns: [/^prison architect/i] },
  { names: ['The Escapists'], patterns: [/^escapists\b/i] },
  { names: ['Gang Beasts'], patterns: [/^gang beasts/i] },
  { names: ['Human Fall Flat'], patterns: [/^human fall flat/i] },
  { names: ['Totally Accurate Battle Simulator', 'TABS'], patterns: [/^totally accurate/i] },
  { names: ['Besiege'], patterns: [/^besiege/i] },
  { names: ['Poly Bridge'], patterns: [/^poly bridge/i] },
  { names: ['Car Mechanic Simulator'], patterns: [/^car mechanic simulator/i] },
  { names: ['House Flipper'], patterns: [/^house flipper/i] },
  { names: ['PowerWash Simulator'], patterns: [/^powerwash simulator/i] },
  { names: ['Gas Station Simulator'], patterns: [/^gas station simulator/i] },
  { names: ['PC Building Simulator'], patterns: [/^pc building simulator/i] },
  { names: ['Thief Simulator'], patterns: [/^thief simulator/i] },
  { names: ['Police Simulator'], patterns: [/^police simulator/i] },
  { names: ['Bus Simulator'], patterns: [/^bus simulator/i] },
  { names: ['Train Simulator'], patterns: [/^train simulator|^train sim world/i] },
  { names: ['Microsoft Flight Simulator'], patterns: [/^microsoft flight simulator/i] },
  { names: ['DCS World'], patterns: [/^dcs world/i] },
  { names: ['War Thunder'], patterns: [/^war thunder/i] },
  { names: ['World of Tanks'], patterns: [/^world of tanks/i] },
  { names: ['World of Warships'], patterns: [/^world of warships/i] },
  { names: ['Crossout'], patterns: [/^crossout/i] },
  { names: ['Enlisted'], patterns: [/^enlisted/i] },
  { names: ['SCUM'], patterns: [/^scum\b/i] },
  { names: ['DayZ'], patterns: [/^dayz\b/i] },
  { names: ['Rust'], patterns: [/^rust\b/i] },
  { names: ['Ark: Survival Evolved', 'Ark'], patterns: [/^ark\b/i] },
  { names: ['Conan Exiles'], patterns: [/^conan exiles/i] },
  { names: ['7 Days to Die'], patterns: [/^7 days to die/i] },
  { names: ['Project Zomboid'], patterns: [/^project zomboid/i] },
  { names: ['State of Decay'], patterns: [/^state of decay/i] },
  { names: ['Dead Rising'], patterns: [/^dead rising/i] },
  { names: ['Left 4 Dead'], patterns: [/^left 4 dead/i] },
  { names: ['Back 4 Blood'], patterns: [/^back 4 blood/i] },
  { names: ['World War Z'], patterns: [/^world war z/i] },
  { names: ['Killing Floor'], patterns: [/^killing floor/i] },
  { names: ['Payday'], patterns: [/^payday\b/i] },
  { names: ['Deep Rock Galactic'], patterns: [/^deep rock galactic/i] },
  { names: ['Vermintide'], patterns: [/^vermintide/i] },
  { names: ['Darktide'], patterns: [/^darktide/i] },
  { names: ['Aliens: Fireteam Elite'], patterns: [/^aliens: fireteam/i] },
  { names: ['Aliens: Dark Descent'], patterns: [/^aliens: dark descent/i] },
  { names: ['Alien: Isolation'], patterns: [/^alien: isolation/i] },
  { names: ['Predator: Hunting Grounds'], patterns: [/^predator: hunting/i] },
  { names: ['Evil Dead'], patterns: [/^evil dead/i] },
  { names: ['Friday the 13th'], patterns: [/^friday the 13th/i] },
  { names: ['Dead by Daylight'], patterns: [/^dead by daylight/i] },
  { names: ['Phasmophobia'], patterns: [/^phasmophobia/i] },
  { names: ['Lethal Company'], patterns: [/^lethal company/i] },
  { names: ['Content Warning'], patterns: [/^content warning/i] },
  { names: ['Helldivers'], patterns: [/^helldivers/i] },
]

interface FranchiseMatch {
  name: string
  title: string
}

/**
 * Extract the franchise/series name from a game title.
 * Returns null for standalone games that don't match any franchise.
 */
export function extractFranchise(title: string): FranchiseMatch | null {
  const cleaned = title.replace(/[[【（][^\]]*[\]】）]/g, '').trim()
  if (!cleaned) return null

  for (const entry of FRANCHISES) {
    for (const pattern of entry.patterns) {
      if (pattern.test(cleaned)) {
        return { name: entry.names[0], title: cleaned }
      }
    }
  }
  return null
}

/**
 * Group an array of titles by franchise.
 * Returns a map of franchise name → game titles,
 * plus a "Other" bucket for ungrouped games.
 */
export function groupByFranchise(
  titles: { title: string; source: string }[],
): { franchise: string; games: number }[] {
  const grouped = new Map<string, number>()

  for (const { title } of titles) {
    const match = extractFranchise(title)
    const key = match ? match.name : 'Other'
    grouped.set(key, (grouped.get(key) ?? 0) + 1)
  }

  return [...grouped.entries()]
    .map(([franchise, games]) => ({ franchise, games }))
    .sort((a, b) => b.games - a.games)
}
